import type { Metadata } from "next";
import { Noto_Sans_Thai } from "next/font/google";
import "./globals.css";
import AllowSound from "@/allow-sound";

// โหลดฟอนต์
const notoSansThai = Noto_Sans_Thai({
  subsets: ["thai", "latin"],
  weight: ["400", "700"], // กำหนดน้ำหนักตัวอักษรที่ต้องใช้
  variable: "--font-noto-sans-thai", // ตั้งค่า CSS Variable (ถ้าต้องการ)
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
        />
        <script src="/js-synthesizer/libfluidsynth-2.3.0.js"></script>
        <script src="/js-synthesizer/libfluidsynth-2.4.6.js"></script>
      </head>
      <body className={`${notoSansThai.className} antialiased`}>
        {/* <AllowSound>{children}</AllowSound> */}
        {children}
      </body>
    </html>
  );
}
